# Generated by Django 3.2.15 on 2022-12-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatin', models.CharField(max_length=126)),
                ('ip', models.CharField(max_length=10)),
                ('port', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=26)),
                ('password', models.CharField(max_length=126)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
