# Generated by Django 3.2.15 on 2022-12-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerastream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camers',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
