# Generated by Django 3.2.15 on 2022-12-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerastream', '0003_rename_locatin_camers_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camers',
            name='login',
            field=models.CharField(blank=True, max_length=26),
        ),
        migrations.AlterField(
            model_name='camers',
            name='password',
            field=models.CharField(blank=True, max_length=126),
        ),
    ]
