# Generated by Django 3.2.15 on 2022-12-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerastream', '0005_entrylog_falseentrylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camers',
            name='port',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
