# Generated by Django 3.2.15 on 2022-12-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=32)),
                ('brand', models.TextField()),
                ('owner', models.TextField()),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=64)),
                ('Name', models.CharField(max_length=64)),
                ('Middle_Name', models.CharField(max_length=64)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_update', models.DateTimeField(auto_now=True)),
                ('left_photo', models.ImageField(upload_to='')),
                ('front_photo', models.ImageField(upload_to='')),
                ('right_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
