# Generated by Django 3.2.15 on 2022-12-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
