# Generated by Django 3.2.15 on 2022-12-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='front_photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
